name: 'Click AI - Run Tests'
description: 'Provide a description here'
author: 'Click AI'

# Define your inputs here.
inputs:
  tests:
    description: 'List of test IDs to run, newline separated'
    required: true
  apiKey:
    description: 'Your API key'
    required: true

branding:
  icon: 'fast-forward'
  color: 'yellow'

runs:
  using: node20
  main: dist/index.js
